apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: herbert-configtool-ingress
  namespace: student-if200207
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: if200207.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /configtool
            pathType: Prefix
            backend:
              service:
                name: herbert-configtool-service
                port:
                  number: 80